license="${mod_license}"
issueTrackerURL="https://github.com/ApolloMonasa/Caps/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/ApolloMonasa/Caps"
logoFile="logo.png"
authors="${mod_authors}"
description='''
让采集变得更高效！
Make Gathering Great Again!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
